### PR TITLE
Add fault injection with 1-byte reads

### LINKED ISSUE #86: Test 1-byte reads
Could there be an option where `read()` only reads 1 byte at a time? It'd be useful to test buffer management routines on parsers.

### PR DESCRIPTION
**Pull request by ligurio**
Closes #86

### CODE REVIEW

**Comment by ligurio** [comment]
@vinipsmaker I made a patch that add a fault injection `errinj_1byte_read` that limits amount of data on every `read()` by a single byte. Could you check that fault injection works for you?

**Comment by vinipsmaker** [comment]
> Could you check that fault injection works for you?

I think I can give it a try by next month.

Thanks for the patch. It should help one of my projects a lot.

**Comment by ligurio** [comment]
> I think I can give it a try by next month.

Good, I will wait for your feedback.

**Comment by ligurio** [comment]
@vinipsmaker How to check the new fault injection with 1-byte read:

```sh
$ git clone https://github.com/ligurio/unreliablefs/
$ git checkout ligurio/gh-86
$ cd unreliablesfs
$ cmake .
$ make -j
$ mkdir source target
$ ./unreliablefs -basedir=./source target/
$ cat << EOF > target/unreliablefs.conf
[errinj_1byte_read]
op_regexp = .*
path_regexp = .*
probability = 80
EOF
$ umount source
```

**Comment by vinipsmaker** [comment]
It's not working at all.

The `read()` syscall returns `-1` and `errno` is set to `EINTR`.

That's the log from `unreliablefs`:

```
errinj_1byte_read triggered on operation 'getattr', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'open', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'read', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'read', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'flush', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'lock', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
errinj_1byte_read triggered on operation 'release', /home/vinipsmaker/Projetos/tabjson/test.BAK/jpat_changes.in
start of 1-byte read
```

Before it hits my call to `read()` the host for my plugin (`gawk`) performs some additional simple calls. My plugin controls the calls to `read()` so that's the part that matters to me.

**Comment by ligurio** [comment]
> It's not working at all.
> The `read()` syscall returns `-1` and `errno` is set to `EINTR`.

Thanks. I'll take a look.

**Pull request closed without merging**
